# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.page_crawler:
        class:     AppBundle\Service\PageCrawler
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
